### ISSUE TITLE
React version 18

### ISSUE THREAD

**Issue by Saf98** [amitavroy/react-vendure-storefront#2]
I am following your youtube tutorial, i have cloned this project into /webclient
When i run the project i get Next.js requires >= 18.2.0 to be installed?
I thought this would break things as stated in video?
i ran npm i which fixed it,
but i am getting apolloError 500

**Comment by amitavroy** [comment]
Well, if you see, this project is quite old. I did a lot of exploration at that time. But I now a lot of things have changed and it's quite possible that the project may not run right now. However, you can still refer to the concepts.
